### ISSUE TITLE
adapting overlays to multiple headset resolutions

### ISSUE THREAD

**Issue by huguesBouvier** [GodotVR/godot_openvr#101]
Hello!

I am new to Godot, I am trying to get a basic overlay working. In a nutshell, I have a viewport setup as an overlay. there is a child texture rectangle that should expand to take the full viewport.

I am rendering a scene on the rectangle. I want to use the rectangle stretching capabilities to make the scene "resolution agnostic" and always be stretched to 1m width in the headset.  

![image](https://user-images.githubusercontent.com/33438817/87888382-7f5f5480-c9e1-11ea-84e4-d361c2372b38.png)

I have several headsets, I noticed that because of resolution, my occulus quest display the overlay significantly bigger that my vive index.

The viewport itself is being scaled correctly to 1m width everytime. The issue is the texture rectangle I am trying to apply scales only to the size of my viewport. That size is ignored because it is overriden when being displayed in VR.

Thus the expand property of the texture rectangle does not work:
![image](https://user-images.githubusercontent.com/33438817/87888417-a3229a80-c9e1-11ea-8547-9b7c010294af.png)

**Comment by beniwtv** [comment]
You can get the size of the VR texture with:

`render_target_size = arvr_interface.get_render_targetsize()`

And assign `render_target_size` to the viewport and your 2D root container in the overlay - everything beyond can be set to expand with that parent.

**Comment by BenMcLean** [comment]
It would help to have that information added to the docs. Thank you!

**Comment by beniwtv** [comment]
Yep, I just updated it.

**Comment by BenMcLean** [comment]
It would be nice to have a clear way to show non-VR stuff without head
tracking on the HMD. Maybe a StereoscopicCamera class that ARVRCamera could
inherit from?

There are a lot more things to do with an HMD than just fully immersive VR.

**Comment by beniwtv** [comment]
You can always do that, though the consensus is without head tracking it would be quite nauseating.
Unless I misunderstand what you are trying to do :)

In any case, open a new issue or proposal for it if needed.
