### ISSUE TITLE
ovr_first_person.tscn seeks its dependency in vr-common instead of godot-xr-tool

### ISSUE THREAD

**Issue by Bebop182** [GodotVR/godot_openvr#112]
The ovr_first_person.tscn scene included in OpenVR plugin from the AssetLib is expecting a vr-common addon that was replaced by godot-xr-tool

**Comment by BastiaanOlij** [comment]
I guess it is time we update it, we've left it alone because the current version of the plugin has all the action stuff in it but i guess it's pretty stable by now.

**Comment by BastiaanOlij** [comment]
The demo project now uses the godot-xr-tools plugin. Also `ovr_first_person.tscn` is no longer dependent on this library.
