### ISSUE TITLE
Change how our release zip file is put together

### ISSUE THREAD

**Issue by BastiaanOlij** [GodotVR/godot_openvr#126]
We need to change two things in how we put the zip file together so we can actually use the zip file as our release in the asset library:
1. the zip file needs a project folder as the root because the asset library will deploy the file from that folder onwards. So the current `addons/godot-openvr` would result in the plugin being dumped into `res://godot-openvr`. 
2. I want to get rid of the godot-openvr-asset repository all together. Right now we read from that repository to build out zip file. We no longer need the files in the root so we can construct the asset completely from this source repository.

The OpenXR plugin already works in this way and is now used to deploy the asset directly to the asset library.

Obviously archiving the godot-openvr-asset repository also means we need to move the wiki to this repository.

**Comment by BastiaanOlij** [comment]
Ben, if you have time for this that would be great, else I'll find a moment to make the needed changes

**Comment by beniwtv** [comment]
Will look at it tomorrow after work :)

**Comment by beniwtv** [comment]
Taken care of in https://github.com/GodotVR/godot_openvr/pull/128
