### ISSUE TITLE
When to prefer OpenVR over OpenXR

### ISSUE THREAD

**Issue by arran-nz** [GodotVR/godot_openvr#131]
Hey @BastiaanOlij and co,

I'm currently using OpenVR in my VR game I am developing. My primary deployment target would be PCVR.

My question is whether to use this library or rather [OpenXR](https://github.com/GodotVR/godot_openxr/).

Could you please enlighten us to the advantages and differences of each?

Thanks!

**Comment by BastiaanOlij** [comment]
Hey Arran,

OpenVR has been around longer and as a result the plugin is more mature then the OpenXR one. However most features are now supported by the OpenXR plugin.

The OpenXR plugin will allow you to deploy your game not just for SteamVR but also directly for the Oculus runtime and on the Quest with more platforms to follow in due time. Also both Oculus and Valve have indicated that they will retire their proprietary runtimes in favor of OpenXR (Oculus even going as far as giving a date for this).

So OpenXR is definitely the choice for the future.

**Comment by arran-nz** [comment]
Okay, thank you for the response!
