### ISSUE TITLE
Does OpenVR for Godot support Windows MR headsets?

### ISSUE THREAD

**Issue by HeadClot** [GodotVR/godot_openvr#29]
Hey @BastiaanOlij - 

I got a Windows MR headset for Christmas. Does OpenVR for Godot support Windows MR headsets?

**Comment by BastiaanOlij** [comment]
Yes it does. Microsoft has got OpenVR drivers for the MR headsets. I'm not sure what the steps are to install it and getting it to work but Jaden (jayhost) has been playing around with his MR headset (though his wish is for it to work on Linux and that I believe is not yet an option for the MR headsets to my knowledge).

**Comment by Dahrkael** [comment]
Yes it does, I'm playing with it as I'm typing this.
The steps are basically installing the headset as you would normally do (this happens automatically when you connect it the first time) and then install *SteamVR* and *Windows Mixed Reality for SteamVR* throught Steam (set both to use beta channel).
Now everytime you launch your game, the MR Portal and SteamVR will launch automatically if they are not already running

**Comment by BastiaanOlij** [comment]
I hope to look at native support for MR headsets, biggest challenge so far looks to be that Microsoft requires you to go through UWP. Not sure how the SteamVR plugin handles that. Once I have a headset I'll be able to experiment:)

Until then, the OpenVR solution seems to do well.

**Comment by HeadClot** [comment]
Ok I have tried this and I can also verify that it works. Going to close this issue :)
