### ISSUE TITLE
[question] Oculus Go / Oculus Quest support

### ISSUE THREAD

**Issue by Jummit** [GodotVR/godot_openvr#50]
Is the Oculus Go supported (and if it is, the Quest will probably work as well), and if not, is it being considered doing? I want to buy a Oculus Quest, which runs a modified version of android, and make some games for it. Will I be able to use Godot?

**Comment by BastiaanOlij** [comment]
Sorry for the very late response, GearVR and Oculus Go (and presumably quest) use the VrApi SDK from Oculus.

We're working on a driver for those here: https://github.com/GodotVR/godot_gearvr but its slow going mostly due to lack of experience on my part with Android.

**Comment by Jummit** [comment]
When will this be usable? Before or after the Quest comes out? I know that the release isn't known yet, but do you need the Quest to make this?

**Comment by BastiaanOlij** [comment]
Yes a Quest would be handy :)

Development of this is situated here: https://github.com/GodotVR/godot_oculus_mobile and right now Fredia has taken the lead on this so its a good idea to keep an eye on his fork here: https://github.com/m4gr3d/godot_oculus_mobile

I'm closing this issue as it is unrelated to OpenVR :)
