### ISSUE TITLE
Secondary Viewports don't run sizing code if the size is set to 0,0

### ISSUE THREAD

**Issue by mrmakeit** [GodotVR/godot_openvr#61]
When rendering to a secondary viewport, Godot doesn't render or run any viewport code if the size is set to 0,0.  As such, the OpenVR code doesn't autosize the viewport.  Setting the viewport to any non-zero size fixes this.

~In Linux, while rendering to the main viewport works exactly as expected, rendering to a secondary viewport results in a skybox being rendered (not the default one from godot), but no other objects are rendered.~

~This has changed as of 3.1.1, as a working project brought from 3.0.6 now exhibits this behavior.  HDR is turned off ( on all viewports as a precaution) arvr is only turned on on the required viewport, and fps is correctly set.  These settings are set both on the viewport object and in the script.~

~Example project showing this bug can be found at https://github.com/mrmakeit/VR-Viewport-Test~

~The PrimaryViewport scene works fine, but the secondaryViewport does not render the actual scene at all on the vive.  The headset is tracked fine, and the primary viewport renders, just the vr viewport does not.~

**Comment by BastiaanOlij** [comment]
See discussion on main godot site. Looks like this was caused because the viewport had no size, that prevents Godot from updating it and getting the required size from OpenVR. Possibly should add a note on that in the readme at some point.

**Comment by mrmakeit** [comment]
I'm going to leave this open and change the title to reflect the actual issue.

**Comment by BastiaanOlij** [comment]
It is an upstream problem though. It is in Godot itself where it skips over viewports sized 0,0 and ARVR never even gets invoked

**Comment by mrmakeit** [comment]
I wasn't certain if it was on the engine side or if it was part of GodotVR.  Closing in favor of godotengine/godot#31400
