### ISSUE TITLE
Possible issue with controller orientation when used with Vive Wireless

### ISSUE THREAD

**Issue by Kotzwinkle** [GodotVR/godot_openvr#68]
I think there *may* be a possible issue when using this add-on in conjunction with the Vive wireless adapter. I Recently got a wireless adapter and noticed that a generic tracker is being slotted into the left hand role (controllerId:1).

Feel free to close if this is a known/configuration issue or if the issue is with the OpenVR SDK.

### Specs

**Processor:** Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 CPUs), ~4.0GHz
**Memory:** 32768MB RAM
**Headset:** 1st gen HTC Vive w/HTC wireless adapter
**Card name:** NVIDIA GeForce GTX 1070

**Godot Version:** v3.1.1.stable.mono.official
**OpenVR module version:** 1.0.4

### Logs

godot
```
Found openvr device 1 (generic_tracker)
Found openvr device 2 (lh_basestation_vive)
Found openvr device 3 (lh_basestation_vive)
Found openvr device 4 (vr_controller_vive_1_5)
Found openvr device 5 (vr_controller_vive_1_5)
Found openvr device 16 (generic_controller)
```

in-script:
```
GetTrackerCount(): 4
tracker0 - index:0, GetName():generic_tracker_1, GetType():Controller, GetHand(): LeftHand
tracker1 - index:1, GetName():vr_controller_vive_1_5_4, GetType():Controller, GetHand(): RightHand
tracker2 - index:2, GetName():vr_controller_vive_1_5_5, GetType():Controller, GetHand(): HandUnknown
tracker3 - index:3, GetName():generic_controller_16, GetType():Controller, GetHand(): HandUnknown
```

in-script (controller context):
```
controller1 - GetControllerId():1, GetName():generic_tracker_1, GetHand():LeftHand
controller2 - GetControllerId():2, GetName():vr_controller_vive_1_5_4, GetHand():RightHand
controller3 - GetControllerId():3, GetName():vr_controller_vive_1_5_5, GetHand():HandUnknown
```

**Comment by BastiaanOlij** [comment]
Did you try a master build? I recently added some code that checks the tracker class and will ensure that only proper controllers are slotted in the left or right hand slot. Generic trackers should get number 3 or up.

**Comment by Kotzwinkle** [comment]
@BastiaanOlij  

That was it! I also ran into the same issue as @rubenjavier here #65 , but was able to correct it by doing master builds for godot/godot-cpp to pick up your recent PR GodotNativeTools/godot-cpp#327

Thanks! I really appreciate the help.

**Comment by BastiaanOlij** [comment]
Perfect! thanks for letting us know :)
