### ISSUE TITLE
Add method for fetching bounds area

### ISSUE THREAD

**Issue by creikey** [GodotVR/godot_openvr#69]
Available from the openVR docs under the `IVRChaperone` class: https://github.com/ValveSoftware/openvr/wiki/IVRChaperone_Overview

This stackoverflow question asked about it:
https://stackoverflow.com/q/58456217/6618110

**Comment by RobKohr** [comment]
Thanks for opening this issue for me! In the mean time, I might just have users plant markers to mark of the bounds for the game manually.

**Comment by beniwtv** [comment]
We could add that API the same way we added other OpenVR APIs (like the overlay stuff), but I am not sure if other VR systems have a similar system and it would be better to make a driver-independent solution?

**Comment by NeoSpark314** [comment]
In the Oculus Mobile Plugin this is implemented here: https://github.com/GodotVR/godot_oculus_mobile/blob/master/src/config/ovr_guardian_system.h . But so far only the function to query the bounding box that fits into the boundary is implemented (`get_boundary_oriented_bounding_box`). It returns an array with a `[Transform, Vector3]`; Maybe the same would be possible for OpenVR?

**Comment by BastiaanOlij** [comment]
Yup, I agree, it should just be a class implemented in the plugin that exposes the logic. 

For Godot 4 enhances once we start working on those I want to add an abstraction for this so there is just one boundary class in Godot that queries the plugin for boundary information and it will work cross platform. But for Godot 3 let's just stick with the approach we did with Oculus Mobile. 

I might do this over the weekend.

**Comment by BastiaanOlij** [comment]
This was done through #83
