### ISSUE TITLE
Demo only works with VR support twice before requiring system restart (Linux).

### ISSUE THREAD

**Issue by georgewsinger** [GodotVR/godot_openvr#72]
I am running the godot_openvr demo in Linux with the following branches:

| **[Sub-]Module**   | **Branch**         |
| ------------------ | ------------------ |
| godot-openvr       | master (default)   |
| godot-cpp          | master (reversion) |
| openvr             | 93df072 (default)  |

**Problem:** I am only able to launch the demo exactly twice before having to restart my machine. If I try to launch the demo a third time (using `pkill godot` each time to close the previous instance), the demo launches but without any VR support. Instead, I only see the demo launch in a godot pancake window, but nothing shows up in my actual Vive HMD, as here:

![](https://i.imgur.com/ych4H7e.png)

When this happens I also see:

    OpenGL ES 2.0 Renderer: GeForce GTX 1070/PCIe/SSE2
    Construct gdnative interface
    ERROR: set_msaa: Index p_msaa=8 out of size (5=5)
       At: scene/main/viewport.cpp:2829.
    Usage count increased to 2
    Usage count increased to 3
    OpenVR: initialising OpenVR context
    
    Application in scene (normal) mode.
    Unable to init VR runtime: Another app was already launching (117)

in the demo's console output.

Also, in case relevant, I frequently see

> "Source 2- Warning: Only one instance of the game can be running at one time."

as here:

![](https://i.imgur.com/Nd2kgqL.png)

aftering launching the demo first time (and I believe sometimes in instances thereafter).

**Comment by beniwtv** [comment]
That Source2 is probably SteamVR Home trying to start - which it can't after the system is in that state.
Does this also happen if you close the window normally instead of using pkill?

**Comment by georgewsinger** [comment]
> Does this also happen if you close the window normally instead of using pkill?

So far it doesn't (after trying 3-4 times).  When launching godot_openvr remotely, is there a  proper way to shut down the program from the console (without closing via GUI window)?

**Comment by georgewsinger** [comment]
Upgrading my nvidia drivers (to 440.26) fixed this issue.
