### ISSUE TITLE
First attempt to get Vive running wit OpenVR and Godot

### ISSUE THREAD

**Issue by new-gen23** [GodotVR/godot_openvr#74]
Hi,

I cloned and compiled Openvr as explained successfully. However, my first stumble is in the readme at the "Linux otes" section: "You can place the libopenvr_api.so file alongside the libgodot_openvr.so file in the bin folder. "
Which "bin" folder are you referring to? Godot? Steam? My programm?

My second stumble is at the line "/home/<user>/.steam/steam/steamapps/" . There is no such folder called "steamapps" in my ./steam/steam folder. Is this because of the broken steam client?

As steam keeps crashing on my Ubuntu, I'd like to use the approach with the run.sh command and bypass as much steam as possible. (yeah I know I gotta use the lib a.s.o)  So I tried the following:
1. Imported the demo from the godot_openvr/demo folder. That runs on my screen find.
2. Exported the demo as a binary to /tmp/vrtest.x86_64
3. run: /home/user/.steam/steam/ubuntu12_32/steam-runtime$ ./run.sh /tmp/vrtest.x86_64
Result:
I see the same output on my screen as when I run the demo directly from godot. (It only throws the recursive error at me: `ERROR: find_by_type_and_id: Condition ' p_tracker_id == 0 ' is true. returned: __null
   At: servers/arvr_server.cpp:305.`

... aaand the Vive remains dark.

How can I debug the problem?

**Comment by new-gen23** [comment]
One more thing: I connected the Vive to my GeForce GTX 1070 via an HDMI to DVI adapter to my secondary out, as the primary HDMI port is used by my monitor.
Do I have to tell the demo somehow where to reach the Vive?

**Comment by new-gen23** [comment]
Ok, I updated the nvidia driver using: 
`apt-get install nvidia-driver-430`
Now the Steam client runs without this error and installed steamvr. 
However, in the console, it threw at least one error:
`steam[2081]: LHR-FFA7BB43: Connected to receiver 3620D4F601
steam[2081]: 3620D4F601: Firmware Version 1124082563 @�kW
steam[2081]: 3620D4F601: ERROR: firmware does not meet minimum required version (1420157645). Please update device.`
But at least steam finally runs its vr room setup. will update...

**Comment by new-gen23** [comment]
ok, good news and bad news. For the first time in about 3 years now, the vive steamvr demo runs under linux  and I can see my controllers + the default room of steamvr. 

bad news: the openvr demo still only runs on the monitor and completely ignores the vive. it remains dark.

**Comment by beniwtv** [comment]
In the demo the .so files are already placed correctly - in demo/addons/godot-openvr/bin/x11/. 

For your own game, make sure to place both libgodot_openvr.so and libopenvr_api.so in the same directory - where depends on your organization, really.

Now run Godot with /home/user/.steam/steam/ubuntu12_32/steam-runtime/run.sh /path/to/godot (or alternatively, the exported project) - alternatively, you could add Godot (or the exported project) to Steam directly "Add non-Steam game...".

If it still remains dark, check the log output in the terminal.

**Comment by new-gen23** [comment]
Ok, update: When I do "run.sh Godot_v3.1.1-stable_x11.64" and open the openvr demo and start it,
I very briefly see the Steam default room, then very shortly the OpenVR Demo and then the app crashes.
The Godot Log loops indefinitely to:

>  servers/arvr_server.cpp:305 - Condition ' p_tracker_id == 0 ' is true. returned: __null

**Comment by new-gen23** [comment]
Update: It works. Partially. The openvr demo crashes as soon as one controller becomes active. 
The error log outputs only warnings, so no problem here.
The main log only says: 
Controller vr_controller_vive_1_5_3 became active
Loading: vr_controller_vive_1_5
** Debug Process Stopped**

**Comment by new-gen23** [comment]
Ok, more insight: 
1. When I place libopenvr_api.so and libgodot_openvr.so in the same folder with the binary of my exported demo, it also works. Nice!
2. I have to close Godot to make the freeze go away. I guess the load was to high for my system to calculate 3 views (vive, duplicate of vive on screen, godo 3d view).
3. When I start the openvr demo, it starts steamvr. When I kill the demo, the steamvr remains running. When I now start the demo again, the vive remains stuck in the SteamVR default room, trying to load the "Steam Home" application but failing. I therefore recommend to stop SteamVR before restarting one's own application.

**Comment by new-gen23** [comment]
I guess since the demo is running, I will gladly close this issue. Thanks for the support!

**Comment by beniwtv** [comment]
If you run the module from the master branch and Godot 3.1 it would crash when activating a controller -> the master version needs Godot 3.2 beta. I do recommend 3.2 anyway, as there have been other improvements for VR.

Also, I ought to fix that p_tracker_id == 0 issue, that is just because in the properties of the left controller the id is 0 when it should be 1.

Glad it works for you now though :)

**Comment by guysoft** [comment]
Hey, I also had an issue with it, I found that it only works if I place the addon binary for linux in:
``res://addons/godot-openvr/bin/x11/``
If I import it seems to import the path to:
``res://godot_openvr_1.1.0/addons/godot-openvr/bin/x11/`` (note the extra godot_openvr_1.1.0 in the project path)
Which then fails to load.
I managed to figure out where to place it thanks the the error output on stdout when running godot from a terminal.
