### ISSUE TITLE
Problems getting basic overlay to work

### ISSUE THREAD

**Issue by Jose-Paulo-FaD** [GodotVR/godot_openvr#85]
I'm following the Overlay [tutorial](https://github.com/GodotVR/godot-openvr-asset/wiki/Using-OpenVR-overlays) available in the openvr asset wiki, but can't get it to work.

My main scene is configured as follows:
```
Spatial
|- ARVROrigin (with Tutorial's _init() script)
    |- ARVRCamera
    |- ARVRController
    |- ARVRController2
|- Viewport (with OpenVR Overlay script)
```

When I run the project, two things happen. I get the console error "Condition ' ptrackerid == 0 ' is true. returned: __null"" and a game window appears, which I can control using my headset, but the overlay does not appear inside SteamVR home.

Thanks in advance.

**Comment by BastiaanOlij** [comment]
@beniwtv any ideas?

**Comment by mrmakeit** [comment]
I assume the ARVROrigin needs to be under viewport, and the _init() script needs to be on the root Spatial object (that's how I understood the tutorial), but even still, I haven't had any success.

I've got a sample project here: https://github.com/mrmakeit/overlay_test  But it doesn't work either.

**Comment by mrmakeit** [comment]
Quick update.

I've tested this SteamVR 1.10.32 and the 1.11.5 Beta with no luck.
Both under Godot 3.2.1 from steam, and under windows 10.

**Comment by Jose-Paulo-FaD** [comment]
@mrmakeit What's the model of your HMD?

**Comment by mrmakeit** [comment]
HTC Vive original

**Comment by Jose-Paulo-FaD** [comment]
> HTC Vive original

I'm using an Odyssey+. I just wanted to make sure it was not a problem specific to WMR.

**Comment by mrmakeit** [comment]
Got it!  Looks like you still have to change `Render Target -> Update Mode` to `Always`.

**Comment by mrmakeit** [comment]
Also, note that this only produces a plane with the camera's view.  As far as I can tell, this does not support any of the 3D mode that steamvr has.  I suspect that's because the support is very limited as is.  (only models from files can be brought in, among other things.)  Please correct me if this isn't the case.  (I was hoping there would be more support beyond just 2D.  Oh well.)

**Comment by BastiaanOlij** [comment]
> Got it! Looks like you still have to change `Render Target -> Update Mode` to `Always`.

That gets me EVERY time, the other common issue is not setting a default size to the viewport, Godot will ignore viewports that aren't sized even though the VR interface will override the size.

**Comment by mrmakeit** [comment]
Yep, see #61.  And godotengine/godot#31400.

**Comment by Jose-Paulo-FaD** [comment]
Also got it working after setting Update Mode to Always.

**Comment by beniwtv** [comment]
Yeah also gets me every time - but I believe the tutorial says to set the viewport size ;)

**Comment by beniwtv** [comment]
I added the update mode to the documentation, as well as expanded the viewport size text to include an example.
I believe this solves this issue.
