### ISSUE TITLE
Overlay rotations inverted in some cases

### ISSUE THREAD

**Issue by mrmakeit** [GodotVR/godot_openvr#88]
While trying to attach a view to a Vive tracker, the rotation of the overlays seems to be inverted (or otherwise different than expected) .  I might be missing something in how transformations work.  When running as a normal app, the rotations seem to work just fine.  I'm currently passing the global_transform from a Point3D to try and orientate an overlay with a model of a real world object.

If none of that makes sense, I can work on posting the project on github as an example.

**Comment by BastiaanOlij** [comment]
@beniwtv any idea?

**Comment by mrmakeit** [comment]
https://github.com/mrmakeit/elite_overlay has an example of this issue.  The keyboard overlay (the content is still a placeholder), doesn't rotate correctly on all axis.  It can be attached to a tracker by changing the control tracker id.  It's currently set to 4 due to being connected to a vive tracker for final usage.  Let me know if you need any more info.

**Comment by beniwtv** [comment]
Yes I still need to check that as well - in detached mode (not tied to a tracker), it works fine, but when attached to a controller the rotations seem weird. 

Even though we're passing the transform to OpenVR the same way both times - but maybe OpenVR requires some changes to the transform.

**Comment by mrmakeit** [comment]
I should point out that the rotation passed doesn't seem accurate even when passed as absolute.  In the example app above, if you change the tracker id to 1 or 2, the rotation is still weird for the other overlay as well.  Taking out the `look_at` command in the keyboard object makes this more obvious.

**Comment by beniwtv** [comment]
There are two different methods to track - one is for tracking absolute, one is tied to a controller (or other tracker-like device)

**Comment by beniwtv** [comment]
Oh I see you used that

**Comment by mrmakeit** [comment]
Yep.  When trying tied to a controller didn't work, I switched to using absolute (because passing global_transformation seemed easier).  Both have exactly the same result.  My guess is that SteamVR handles rotations using a different axis configuration than Godot, but couldn't get the math to work right.

**Comment by beniwtv** [comment]
Yes, basically we have two functions to convert from OpenVR to Godot, and vice-versa.

https://github.com/GodotVR/godot_openvr/blob/master/src/open_vr/openvr_data.cpp#L1127

I wonder if something is messed up from Godot to OpenVR.

**Comment by mrmakeit** [comment]
Any update on this?  I've poked around in the functions mentioned above, but didn't see anything obviously wrong.

**Comment by beniwtv** [comment]
Nope, sorry, work is keeping me quite busy at the moment - I plan to have a look as soon as I can though.

**Comment by beniwtv** [comment]
ok, thanks to your overlay example project, I did see all axes are inverted. Now working out a fix!

**Comment by beniwtv** [comment]
So, apparently OpenVR requires an inverse() of the basis. Can you try the following change:

Between these lines: 
https://github.com/GodotVR/godot_openvr/blob/master/src/open_vr/openvr_data.cpp#L1152

`transform->basis = transform->basis.inverse()`

I can also provide a Linux build (sorry no Windows, as I currently do not have that set up).

**Comment by mrmakeit** [comment]
Interesting.  I'm still waiting on my Index to be shipped, so my Linux machine currently doesn't have a headset hooked up to it.  I'll see about putting together a Windows build to see if that helps.

**Comment by beniwtv** [comment]
Fixed now in master code (and Linux build). Used your Elite overlay as well to verify.

@BastiaanOlij Would you be able to update the Windows build? (Linux is uploaded already)
