### ISSUE TITLE
OpenVR crashes on Linux Manjaro with HTC Vive

### ISSUE THREAD

**Issue by redhoot-dev** [GodotVR/godot_openvr#91]
Complete noob when it comes to VR, but I managed to get it working fine on windows, and been trying to get it to work on Linux. Godot itself runs just fine and the basic tutorial scene im following works on windows. But Linux is my main dev station. 

Here`s a terminal dump :

`Running: /home/statix/Downloads/Godot_v3.2.1-stable_x11.64 --path /home/statix/Dropbox/work/godotVR --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 18022 --position 768,420
Godot Engine v3.2.1.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX TITAN X/PCIe/SSE2
 
Usage count increased to 2
Usage count increased to 3
OpenVR: initialising OpenVR context

Application in scene (normal) mode.
Main OpenVR interface has been initialized
Main render models interface has been initialized.
Found base station 1 (lh_basestation_vive)
Found base station 2 (lh_basestation_vive)
Found controller 3 (vr_controller_vive_1_5)
Found controller 4 (vr_controller_vive_1_5)
Found controller 16 (generic_controller)
Controller vr_controller_vive_1_5_3 became active
Loading: vr_controller_vive_1_5
Controller vr_controller_vive_1_5_4 became active
Loading: vr_controller_vive_1_5
shaders/vulkan/distort_vs.spv
shaders/vulkan/distort_vs_layered.spv
shaders/vulkan/distort_vs_nd.spv
shaders/vulkan/distort_vs_latest_nd.spv
shaders/vulkan/distort_vs_layered_nd.spv
shaders/vulkan/distort_vs_reproject.spv
shaders/vulkan/distort_vs_reproject_nd.spv
shaders/vulkan/distort_vs_reproject_mv.spv
shaders/vulkan/distort_geom_vs.spv
shaders/vulkan/distort_geom_curved_vs.spv
shaders/vulkan/distort_geom_uvs_embedded_vs.spv
shaders/vulkan/distort_geom_curved_uvs_embedded_vs.spv
shaders/vulkan/distort_geom_ptnorm_vs.spv
shaders/vulkan/distort_geom_ptnorm_curved_vs.spv
shaders/vulkan/distort_geom_ptnorm_uvs_embedded_vs.spv
shaders/vulkan/distort_geom_ptnorm_curved_uvs_embedded_vs.spv
shaders/vulkan/distort_geom_fresnel_vs.spv
shaders/vulkan/distort_geom_vignette_vs.spv
shaders/vulkan/distort_geom_aa_lines_vs.spv
shaders/vulkan/distort_geom_aa_circles_vs.spv
shaders/vulkan/distort_geom_hard_bounds_aa_lines_vs.spv
shaders/vulkan/distort_geom_hard_bounds_aa_squares_vs.spv
shaders/vulkan/distort_geom_aa_quads_vs.spv
shaders/vulkan/distort_geom_grid_vs.spv
shaders/vulkan/distort_none_vs.spv
shaders/vulkan/distort_panorama_vs.spv
shaders/vulkan/panel_mask_vs.spv
shaders/vulkan/downsample_vs.spv
shaders/vulkan/msaa_resolve_vs.spv
shaders/vulkan/tracked_camera_vs.spv
shaders/vulkan/tracked_camera_undistort_vs.spv
shaders/vulkan/tracked_camera_edgefilter_vs.spv
shaders/vulkan/tracked_camera_reprojection_vs.spv
shaders/vulkan/tracked_camera_lines_vs.spv
shaders/vulkan/gpu_measurement_vs.spv
shaders/vulkan/frame_hallucination_vs.spv
shaders/vulkan/motion_smoothing_debug_vs.spv
shaders/vulkan/motion_filter_vs.spv
shaders/vulkan/motion_filter_early_out_vs.spv
shaders/vulkan/unlit_vs.spv
shaders/vulkan/distort_ps.spv
shaders/vulkan/distort_ps_gamma.spv
shaders/vulkan/distort_ps_layered.spv
shaders/vulkan/distort_ps_mc.spv
shaders/vulkan/distort_ps_gamma_mc.spv
shaders/vulkan/distort_ps_layered_mc.spv
shaders/vulkan/distort_ps_nd.spv
shaders/vulkan/distort_ps_gamma_nd.spv
shaders/vulkan/distort_ps_layered_nd.spv
shaders/vulkan/distort_ps_mc_nd.spv
shaders/vulkan/distort_ps_gamma_mc_nd.spv
shaders/vulkan/distort_ps_layered_mc_nd.spv
shaders/vulkan/distort_ps_scene.spv
shaders/vulkan/distort_ps_scene0.spv
shaders/vulkan/distort_ps_scene_blur.spv
shaders/vulkan/distort_geom_ps.spv
shaders/vulkan/distort_geom_multitap_ps.spv
shaders/vulkan/distort_geom_reflect_ps.spv
shaders/vulkan/distort_geom_reflect_multitap_ps.spv
shaders/vulkan/distort_geom_fresnel_ps.spv
shaders/vulkan/distort_geom_vignette_ps.spv
shaders/vulkan/distort_geom_aa_lines_ps.spv
shaders/vulkan/distort_geom_aa_circles_ps.spv
shaders/vulkan/distort_geom_hard_bounds_aa_lines_ps.spv
shaders/vulkan/distort_geom_hard_bounds_aa_squares_ps.spv
shaders/vulkan/distort_geom_aa_quads_ps.spv
shaders/vulkan/distort_geom_grid_ps.spv
shaders/vulkan/distort_none_ps.spv
shaders/vulkan/distort_none_ps_gamma.spv
shaders/vulkan/distort_none_ps_layered.spv
shaders/vulkan/distort_panorama_ps.spv
shaders/vulkan/distort_panorama_dome_ps.spv
shaders/vulkan/distort_panorama_dome_radius_ps.spv
shaders/vulkan/panel_mask_ps.spv
shaders/vulkan/downsample_ps.spv
shaders/vulkan/downsample_srgb_ps.spv
shaders/vulkan/downsample_filter_x_ps.spv
shaders/vulkan/downsample_filter_x_srgb_ps.spv
shaders/vulkan/downsample_filter_y_ps.spv
shaders/vulkan/downsample_filter_y_srgb_ps.spv
shaders/vulkan/msaa_resolve_2x_ps.spv
shaders/vulkan/msaa_resolve_4x_ps.spv
shaders/vulkan/msaa_resolve_8x_ps.spv
shaders/vulkan/tracked_camera_ps.spv
shaders/vulkan/tracked_camera_undistort_ps.spv
shaders/vulkan/tracked_camera_edgefilter_ps.spv
shaders/vulkan/tracked_camera_reprojection_ps.spv
shaders/vulkan/tracked_camera_lines_ps.spv
shaders/vulkan/gpu_measurement_ps.spv
shaders/vulkan/frame_hallucination_ps.spv
shaders/vulkan/motion_smoothing_debug_ps.spv
shaders/vulkan/motion_filter_attenuation_ps.spv
shaders/vulkan/motion_filter_median_ps.spv
shaders/vulkan/motion_filter_cost_ps.spv
shaders/vulkan/motion_filter_blur_ps.spv
shaders/vulkan/unlit_ps.spv
shaders/vulkan/unlit_sint16_ps.spv
shaders/vulkan/unlit_motion_vectors_ps.spv
shaders/vulkan/unlit_motion_cost_ps.spv
shaders/vulkan/unlit_convert_to_nv12_ps.spv
shaders/vulkan/unlit_motion_color_diff_ps.spv
shaders/vulkan/unlit_motion_vector_diff_ps.spv
shaders/vulkan/unlit_motion_attenuation_ps.spv
shaders/vulkan/distort_cs.spv
shaders/vulkan/distort_cs_mc.spv
shaders/vulkan/linepixelsim_cs.spv
shaders/vulkan/linepixelsim2_cs.spv
shaders/vulkan/testgrid_cs.spv
shaders/vulkan/motionvector_cost_cs.spv
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238.
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x3bd70) [0x7fca4fff6d70] (??:0)
[2] /home/statix/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrclient.so(+0x25af12) [0x7fca28d0cf12] (??:0)
[3] /home/statix/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrclient.so(+0x109222) [0x7fca28bbb222] (??:0)
[4] /home/statix/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrclient.so(+0x29f230) [0x7fca28d51230] (??:0)
[5] /usr/lib/libpthread.so.0(+0x946f) [0x7fca4fc6c46f] (??:0)
[6] /usr/lib/libc.so.6(clone+0x43) [0x7fca500ba3d3] (??:0)
-- END OF BACKTRACE --`

**Comment by redhoot-dev** [comment]
Should mention I followed the examples in the readme, both setting paths and launching through steam gives the same error.

Im sure its a user error but I`m not sure where to look.

**Comment by beniwtv** [comment]
I am using Manjaro myself, not seeing any crash - can you let me know what version of the OpenVR assset you are using?

**Comment by redhoot-dev** [comment]
A reboot solved my issue for some reason. Nothing to see here. Thanks for replying!
